version: '3.8'

services:
    team_management_api:
        image: teammanagement:dev
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - team_management_db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=postgres;Database=team_management_db
 
    team_management_db:
       image: postgres:15
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: team_management_db
       ports:
         - "5432:5432"
       volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: